(tests) added F90 tests to the automated test suite; check that output png files exist and are non-zero size

diff --git a/test/F90/Makefile.am b/test/F90/Makefile.am
--- a/test/F90/Makefile.am
+++ b/test/F90/Makefile.am
@@ -4,8 +4,26 @@ LDADD = ../../src/libpgplot.la
 
 CLEANFILES = *.png
 
-ftests = test-2D test-fortran test-pgaxis test-pgncur
+ftests = test-2D test-fortran test-pgaxis #test-pgncur
 
-#TESTS = $(ftests)
+TESTS = $(ftests)
 check_PROGRAMS = $(ftests)
 AM_DEFAULT_SOURCE_EXT = .f90
+
+# Ensure that the tests are built as part of the 'check' target
+check: check_output_files $(ftests)
+
+test_output_files = giza-test.png giza-test-2D.png
+
+# Custom target to check for the existence of expected output files from the Fortran tests
+check_output_files:
+	@echo "Checking for required png files..."
+	@for i in $(test_output_files); do \
+	    if [ ! -s $$i ]; then \
+	        echo "ERROR: Required file $$i does not exist."; \
+	        exit 1; \
+	    else \
+	        echo "$$i exists"; \
+	    fi; \
+	done
+	@echo "All required png files exist."
